# finally return #
(let output =
    (try
        (puts: "error-" error)
        (assert: (error != nil) "")
        (Error: "self-defined error")
    catch
        (puts: "hello" Error Error)
        (puts: "hello" error)
        (puts: "hello" (error type))
        (puts: "hello" (error to_s))
        (puts: "hello" ((error to_b) == false))
        (puts: "hello" (Error == Error))
        (puts: "hello" (error message))
        #(puts: Error (Error: "except"))#
    finally
        (puts: "well done")
    )
)
(assert: (output == nil) "test try expression value")